name: PR me, baby, one more time

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Generate branch and PR
        uses: ./.github/workflows/daily-template
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
