name: PR me, baby, one more time

on:
  push
  # schedule:
  #   - cron: "0 8 * * *"

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Generate branch and PR
        uses: actions/checkout@master
        run: npm run pr
