name: PR me, baby, one more time

on:
  push
  # schedule:
  #   - cron: "0 8 * * *"

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Generate branch and PR
        run: ./.github/workflows/daily-post-template/entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
