name: Trigger mamuso.net build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  step:
    name: Trigger mamuso.net build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger 🛎️
        run: |
          curl -X POST https://api.github.com/repos/mamuso/mamuso.net/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "New entry on mamuso.dev", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
